<?php

namespace AppBundle\Repository;

/**
 * AvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvesRepository extends \Doctrine\ORM\EntityRepository
{
}
