<?php

namespace AppBundle\Repository;

/**
 * New_passwordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class New_passwordRepository extends \Doctrine\ORM\EntityRepository
{
}
