<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function  getObervationByUserId($user_id)
    {

        $qb = $this->createQueryBuilder('o');
        $qb->select('o')
            ->where('o.user = :user')
            ->setParameter('user',$user_id);

        return $qb->getQuery()->getResult();
    }
}
