<?php

namespace AppBundle\Repository;

/**
 * Password_registrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Password_registrationRepository extends \Doctrine\ORM\EntityRepository
{
}
